In [1]:
import numpy as np
import keras
from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt

Using TensorFlow backend.


In [2]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [3]:
fashion_mnist = keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [6]:
xt1 = x_train[:3]; yt1 = y_train[:3]

In [11]:
shape = np.shape(xt1)
shape[1]

28

In [19]:
xt = xt1.reshape(shape[0],shape[1]*shape[2])

In [20]:
np.shape(xt)

(3, 784)

In [21]:
xt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [34]:
xxx = xx.T
np.shape(xxx)

(784, 3)

In [36]:
xxx[0]

array([0, 0, 0], dtype=uint8)

In [26]:
x[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [28]:
np.shape(xx[0])

(784,)

In [37]:
a = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
b = a.reshape(2,4)
np.shape(b)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
c = b.T
np.shape(c)
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
c[0]

array([1, 5])

In [44]:
d = np.ones((2,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
e = np.dot(c,d)
e

array([[ 6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.],
       [10., 10., 10., 10.],
       [12., 12., 12., 12.]])

In [8]:
def image_of_each_class(dataset):
    
    train_images = dataset['x_train']
    train_labels = dataset['y_train']
    
    sample_images = []
    sample_labels = []
    for i in range(len(class_names)):
        index = np.argmax(train_labels == i)
        img = train_images[index]
        lbl = class_names[train_labels[index]]
        sample_images.append(img)
        sample_labels.append(lbl)
        
    return sample_images,sample_labels

In [9]:
sample_images,sample_labels = image_of_each_class(dataset)

In [10]:
wandb.log({"examples": [wandb.Image(image, caption=label) for image,label in zip(sample_images,sample_labels)]})

wandb: Currently logged in as: rishi_m (use `wandb login --relogin` to force relogin)


True

In [25]:
images = []
labels = []
for i in range(10):
    
    pixels = x_train[ind].reshape((28, 28))
    images.append(pixels)
    labels.append(class_names[y_train[ind]])


ValueError: Un-supported shape for image conversion [10, 28, 28]

In [26]:
len(images)

10

In [14]:
images

array([], dtype=float64)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
#x = np.argmax(arr == 4)
print(x)

In [19]:
a = np.array([])
for i in range (3):
    a = np.append(a,i)
a

array([0., 1., 2.])