In [35]:
import numpy as np
import keras
from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt

In [36]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x) *(1-sigmoid (x))

def softmax(A):
    return np.exp(A) / np.sum(np.exp(A), axis=0) #expA (axis=0, keepdims=True)

In [37]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [38]:
fashion_mnist = keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [42]:
y_train[:3]

array([9, 0, 0], dtype=uint8)

In [5]:
a = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
x = a.reshape(2,4)
np.shape(x[0])[0]

4

In [7]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
no_hidden_layers = 3 # no of hidden layers
no_neuron_hidden = 4 # no. of neurons in each hidden layers
no_neuron_output = 3 # # no. of neurons in each hidden layers

In [9]:
size_input_layer = np.shape(x[0])[0]
size_hidden_layer = no_neuron_hidden
size_output_layer = no_neuron_output

In [10]:
layer_dims = [size_input_layer]+ [size_hidden_layer]*no_hidden_layers+ [size_output_layer]

In [11]:
layer_dims

[4, 4, 4, 4, 3]

In [12]:
def initialize_parameters(layer_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the dimensions of each layer in our network
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
                    bl -- bias vector of shape (layer_dims[l], 1)
    """
    
    #np.random.seed(0)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
        
        parameters['w' + str(l)] = np.ones((layer_dims[l], layer_dims[l-1])) 
        parameters['b' + str(l)] = np.ones((layer_dims[l], 1))
        
        assert(parameters['w' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters

In [13]:
param = initialize_parameters(layer_dims)

In [34]:
len(param)

8

In [18]:
def linear_forward(A, W, b):
    """
    Implement the linear part of a layer's forward propagation.

    Arguments:
    A -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter 
    cache -- a python tuple containing "A", "W" and "b" ; stored for computing the backward pass efficiently
    """
    
    Z = np.dot(W, A) + b

    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [27]:
w1 = param["w1"]; b1 = param["b1"]
b1

array([[1.],
       [1.],
       [1.],
       [1.]])

In [28]:
np.shape(w1)

(4, 4)

In [29]:
Z = np.dot(w1, x.T) #+ b1

In [30]:
Z

array([[10., 26.],
       [10., 26.],
       [10., 26.],
       [10., 26.]])

In [31]:
np.shape(Z)

(4, 2)

In [32]:
Z = linear_forward(x.T, w1, b1)
Z

(array([[11., 27.],
        [11., 27.],
        [11., 27.],
        [11., 27.]]),
 (array([[1, 5],
         [2, 6],
         [3, 7],
         [4, 8]]),
  array([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
  array([[1.],
         [1.],
         [1.],
         [1.]])))

In [33]:
def linear_activation_forward(A_prev, W, b, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    A -- the output of the activation function, also called the post-activation value 
    cache -- a python tuple containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently
    """
    
    if activation == "sigmoid":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        ### START CODE HERE ### (≈ 2 lines of code)
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
        ### END CODE HERE ###
    
    elif activation == "relu":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        ### START CODE HERE ### (≈ 2 lines of code)
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
        ### END CODE HERE ###
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)

    return A, cache


NameError: name 'w' is not defined

array([0.9999833, 0.9999833, 0.9999833, 0.9999833])