In [1]:
import numpy as np
import keras
from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt

Using TensorFlow backend.


In [107]:
def sigmoid(a):
    s = 1/(1+np.exp(-a))
    return s

def derivative_sigmoid(a):
    ds = sigmoid(a) *(1-sigmoid (a))
    return ds

def tanh(a):
    t=(np.exp(a)-np.exp(-a))/(np.exp(a)+np.exp(-a))
    return t

def derivative_tanh(a):
    dt=1-tanh(a)**2
    return dt


def softmax(a):
    return np.exp(a) / np.sum(np.exp(a))#, axis=0) #expA (axis=0, keepdims=True)

In [108]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [109]:
a = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [110]:
x = a.reshape(2,4)
np.shape(x[0])[0]

4

In [78]:
no_hidden_layers = 2 # no of hidden layers
no_neuron_hidden = 4 # no. of neurons in each hidden layers
no_neuron_output = 2 # # no. of neurons in each hidden layers

In [79]:
size_input_layer = np.shape(x[0])[0]
size_hidden_layer = no_neuron_hidden
size_output_layer = no_neuron_output

In [80]:
layer_dimensions = [size_input_layer]+ [size_hidden_layer]*no_hidden_layers+ [size_output_layer]
layer_dimensions

[4, 4, 4, 2]

In [81]:
def initialize_parameters(layer_dimensions):
    """
    Arguments:
    layer_dims -- python array (list) containing the dimensions of each layer in our network
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
                    bl -- bias vector of shape (layer_dims[l], 1)
    """
    
    #np.random.seed(0)
    parameters = {}
    L = len(layer_dimensions)            # number of layers in the network

    for k in range(1, L):
        
        parameters['w' + str(k)] = np.ones((layer_dimensions[k], layer_dimensions[k-1])) 
        parameters['b' + str(k)] = np.ones((layer_dimensions[k]))#, 1))
        
#         assert(parameters['w' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
#         assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))    
    return parameters

In [82]:
param = initialize_parameters(layer_dimensions)
param

{'w1': array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 'b1': array([1., 1., 1., 1.]),
 'w2': array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 'b2': array([1., 1., 1., 1.]),
 'w3': array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 'b3': array([1., 1.])}

In [83]:
x.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [84]:
np.shape(x.T)

(4, 2)

In [2]:
def linear_agrregation(h, w, b):
    """
    Implement the linear part of a layer's forward propagation.

    Arguments:
    h -- activations from previous layer (or input data): (size of previous layer, number of examples)
    w -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    a -- the input of the activation function, also called pre-activation parameter 
    temp -- a python tuple containing "h", "w" and "b" ; stored for computing the backward pass efficiently
    """
    
    a = np.dot(w, h) + b

    #assert(Z.shape == (W.shape[0], A.shape[1]))
    temp = (h,w,b)
    
    return a, temp

In [4]:
a,temp = linear_agrregation(x[0],param['w1'],param['b1'])
temp

NameError: name 'x' is not defined

In [5]:
def activation(h_prev, w, b, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer

    Arguments:
    h_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    w -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    h -- the output of the activation function, also called the post-activation value 
    cache -- a python tuple containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently
    """
    
    if activation == "sigmoid":

        a, linear_temp = linear_agrregation(h_prev, w, b)
        h = sigmoid(a)
    
    elif activation == "tanh":
        a, linear_temp = linear_agrregation(h_prev, w, b)
        h = tanh(a)
        
    elif activation == "softmax":
        a, linear_temp = linear_agrregation(h_prev, w, b)
        h = softmax(a)
    
    
#     assert (A.shape == (W.shape[0], A_prev.shape[1]))
    temp = (linear_temp, a)

    return h, temp

In [6]:
activation(x,param['w1'],param['b1'],"sigmoid")

NameError: name 'x' is not defined

In [133]:
len(param)//2

3

In [134]:
for i in range(3-1):
    print(i+1)

1
2


In [139]:
def forward_pass(x, parameters):
    """
    Implement forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID computation
    
    Arguments:
    X -- data, numpy array of shape (input size, number of examples)
    parameters -- output of initialize_parameters_deep()
    
    Returns:
    AL -- last post-activation value
    caches -- list of caches containing:
                every cache of linear_activation_forward() (there are L-1 of them, indexed from 0 to L-1)
    """

    temps = []
    #hL = []
    h = x
    L = len(parameters) // 2                  # number of layers in the neural network
    
    # Implement [LINEAR -> RELU]*(L-1). Add "cache" to the "caches" list.
    for k in range(L-1):
        l = k+1
        h_prev = h 
        h,temp = activation(h_prev, parameters['w'+str(l)], parameters['b'+str(l)], activation="sigmoid")
        temps.append(temp)
        #hL.append(h)
    
    # Implement LINEAR -> SIGMOID. Add "cache" to the "caches" list.
    hL,temp1 = activation(h, parameters['w'+str(L)], parameters['b'+str(L)], activation="softmax")
    temps.append(temp1)
    
    #assert(AL.shape == (1,X.shape[1]))
            
    return hL, temps

In [140]:
zz, temps = forward_pass(x[0], param)

In [141]:
zz

array([0.5, 0.5])

In [142]:
temps

[((array([1, 2, 3, 4]),
   array([[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]),
   array([1., 1., 1., 1.])),
  array([11., 11., 11., 11.])),
 ((array([0.9999833, 0.9999833, 0.9999833, 0.9999833]),
   array([[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]),
   array([1., 1., 1., 1.])),
  array([4.99993319, 4.99993319, 4.99993319, 4.99993319])),
 ((array([0.9933067, 0.9933067, 0.9933067, 0.9933067]),
   array([[1., 1., 1., 1.],
          [1., 1., 1., 1.]]),
   array([1., 1.])),
  array([4.97322682, 4.97322682]))]

In [144]:
zz

array([0.5, 0.5])

In [146]:
softmax([4.97322682, 4.97322682])

array([0.5, 0.5])